import { AppState, User } from './types'

export const mockUsers: User[] = [
  {
    id: 'u1',
    email: 'admin@toriba.com',
    name: 'Admin CEO',
    role: 1,
    phone: '+5511999999991',
    password: '123',
  },
  {
    id: 'u2',
    email: 'gerente@toriba.com',
    name: 'Gerente',
    role: 2,
    phone: '+5511999999992',
    password: '123',
  },
  {
    id: 'u3',
    email: 'peao@toriba.com',
    name: 'Operacional',
    role: 3,
    phone: '+5511999999993',
    password: '123',
  },
]

export const initialData: AppState = {
  isAuthenticated: false,
  currentUser: null,
  notifiedAlertIds: [],
  userRole: 1,
  isOnline: true,
  pendingSyncQueue: [],
  lastSync: new Date().toISOString(),
  users: mockUsers,
  pastos: [
    {
      id: 'p1',
      name: 'Piquete Maternidade',
      status: 'Ocupado',
      loteId: 'l1',
      grassHeight: 18,
      capacity: 50,
      area: 12,
      taxaLotacao: 45,
      idealEntryHeight: 35,
      minExitHeight: 20,
    },
    {
      id: 'p2',
      name: 'Pasto Fundo',
      status: 'Livre',
      grassHeight: 40,
      capacity: 100,
      area: 25,
      taxaLotacao: 0,
      idealEntryHeight: 35,
      minExitHeight: 20,
    },
  ],
  lotes: [
    { id: 'l1', name: 'Matrizes PO Elite', costCenter: 'CC01-PO' },
    { id: 'l2', name: 'Garrotes Engorda TIP', costCenter: 'CC02-TIP' },
  ],
  animais: [
    {
      id: 'a1',
      brinco: '001',
      rgn: 'NEL123',
      nomeAnimal: 'Matriz Alfa PO',
      loteId: 'l1',
      categoria: 'Matriz PO',
      pesoEntrada: 400,
      pesoAtual: 550,
      gmd: 0.1,
      status: 'Ativo',
      birthDate: '2020-05-10',
      costCenter: 'CC01-PO',
      gender: 'F',
      custoAcumulado: 120,
    },
    {
      id: 'a3',
      brinco: '101',
      nomeAnimal: 'Garrote Beta',
      loteId: 'l2',
      categoria: 'Garrote TIP',
      pesoEntrada: 250,
      pesoAtual: 320,
      gmd: 1.2,
      status: 'Ativo',
      birthDate: '2023-08-20',
      costCenter: 'CC02-TIP',
      gender: 'M',
      custoAcumulado: 85,
    },
  ],
  pesagens: [{ id: 'ps1', animalId: 'a1', weight: 500, date: '2023-08-01T10:00:00.000Z' }],
  reproducoes: [
    {
      id: 'r1',
      animalId: 'a1',
      type: 'IATF',
      date: '2023-10-01',
      dataD0: '2023-09-20',
      dataIATF: '2023-10-01',
      previsaoToque: '2023-10-31',
      dpp: new Date(new Date().getTime() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'Prenhe',
    },
    {
      id: 'r2',
      animalId: 'a3',
      type: 'IATF',
      date: '2023-08-01',
      touro: 'REM Armador',
      previsaoToque: '2023-08-31',
      dpp: new Date(new Date().getTime() - 100 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'Vazia',
    },
  ],
  estoque: [
    {
      id: 'e1',
      name: 'Sal Mineral (Saco 30kg)',
      category: 'Nutrição',
      quantity: 40,
      unit: 'Kg',
      unitCost: 2.5,
      minStock: 100,
    },
    {
      id: 'e2',
      name: 'Sêmen Touro REM Armador',
      category: 'Sêmen',
      quantity: 200,
      unit: 'Doses',
      unitCost: 45.0,
      botijao: 'BT-01',
      caneca: 'C-05',
    },
    {
      id: 'e3',
      name: 'Milho Grão',
      category: 'Nutrição',
      quantity: 5000,
      unit: 'Kg',
      unitCost: 1.2,
      minStock: 2000,
    },
    {
      id: 'e4',
      name: 'Farelo de Soja',
      category: 'Nutrição',
      quantity: 2000,
      unit: 'Kg',
      unitCost: 2.8,
      minStock: 1000,
    },
    {
      id: 'e5',
      name: 'Ureia Pecuária',
      category: 'Nutrição',
      quantity: 500,
      unit: 'Kg',
      unitCost: 3.5,
      minStock: 200,
    },
    {
      id: 'er1',
      name: 'Ração Engorda TIP 18%',
      category: 'Nutrição',
      quantity: 1500,
      unit: 'Kg',
      unitCost: 1.85,
      minStock: 500,
    },
  ],
  formulacoes: [
    {
      id: 'f1',
      name: 'Ração Engorda TIP 18%',
      ingredients: [
        { itemId: 'e3', percent: 70 },
        { itemId: 'e4', percent: 25 },
        { itemId: 'e5', percent: 5 },
      ],
    },
  ],
  producoesRacao: [],
  manejos: [
    {
      id: 'mn1',
      type: 'Nutrição',
      details: 'Trato Diário',
      date: new Date(Date.now() - 2 * 86400000).toISOString(),
      loteId: 'l2',
      cost: 1250,
      itemId: 'e1',
      quantity: 50,
    },
    {
      id: 'mn2',
      type: 'Nutrição',
      details: 'Trato Diário',
      date: new Date(Date.now() - 1 * 86400000).toISOString(),
      loteId: 'l2',
      cost: 1300,
      itemId: 'e1',
      quantity: 52,
    },
  ],
  parceiros: [
    {
      id: 'parc1',
      Nome_Razao_Social: 'Agropecuária Boi Gordo Ltda',
      Tipo_Documento: 'CNPJ',
      Numero_Documento: '12.345.678/0001-90',
      Telefone_WhatsApp: '5511999999999',
      Email: 'contato@boigordo.com.br',
      Categoria_Parceiro: ['Cliente'],
      Status: 'Ativo',
      ID_Inttegra: 'INT-C01',
    },
    {
      id: 'parc2',
      Nome_Razao_Social: 'Nutrição Animal S.A.',
      Tipo_Documento: 'CNPJ',
      Numero_Documento: '98.765.432/0001-10',
      Telefone_WhatsApp: '5511888888888',
      Email: 'vendas@nutricaoanimal.com.br',
      Categoria_Parceiro: ['Fornecedor'],
      Status: 'Ativo',
      ID_Inttegra: 'INT-F01',
    },
  ],
  transacoes: [
    {
      id: 't1',
      Descricao_Lancamento: 'Venda Bezerros Mestiços',
      Valor_Total: 45000,
      Tipo_Movimento: 'Receita',
      Classificacao_Custo: 'Variável',
      Data_Competencia: new Date().toISOString(),
      Data_Vencimento: new Date(new Date().getTime() - 2 * 86400000).toISOString(), // Atrasado 2 dias
      Data_Efetivacao_Real: undefined,
      Centro_Custo_Direcionado: 'CC02-Comercial TIP',
      Status_Pagamento: 'Atrasado',
      Macroconta_Inttegra: '1. RECEITAS',
      Categoria_Inttegra: 'Receitas Pecuárias',
      Subcategoria_Detalhe: 'Machos Abate',
      Parceiro_Vinculado: 'parc1',
    },
    {
      id: 't2',
      Descricao_Lancamento: 'Venda Lote Matrizes Descarte',
      Valor_Total: 30000,
      Tipo_Movimento: 'Receita',
      Classificacao_Custo: 'Variável',
      Data_Competencia: new Date().toISOString(),
      Data_Vencimento: new Date(new Date().getTime() + 2 * 86400000).toISOString(),
      Centro_Custo_Direcionado: 'CC02-Comercial TIP',
      Status_Pagamento: 'Pendente',
      Macroconta_Inttegra: '1. RECEITAS',
      Categoria_Inttegra: 'Receitas Pecuárias',
      Subcategoria_Detalhe: 'Fêmeas Descarte',
      Parceiro_Vinculado: 'parc1',
    },
    {
      id: 't3',
      Descricao_Lancamento: 'Sêmen Elite ABS',
      Valor_Total: 5500,
      Tipo_Movimento: 'Despesa',
      Classificacao_Custo: 'Variável',
      Data_Competencia: new Date().toISOString(),
      Data_Vencimento: new Date(new Date().getTime() + 24 * 60 * 60 * 1000).toISOString(),
      Centro_Custo_Direcionado: 'CC01-Nelore PO',
      Status_Pagamento: 'Pendente',
      Macroconta_Inttegra: '5. PECUÁRIA (Custos Diretos)',
      Categoria_Inttegra: 'Insumos Rebanho Genética',
      Subcategoria_Detalhe: 'Sêmen',
      Parceiro_Vinculado: 'parc2',
    },
    {
      id: 't4',
      Descricao_Lancamento: 'Energia Elétrica Sede',
      Valor_Total: 1200,
      Tipo_Movimento: 'Despesa',
      Classificacao_Custo: 'Fixo',
      Data_Competencia: new Date().toISOString(),
      Data_Vencimento: new Date().toISOString(),
      Centro_Custo_Direcionado: 'CC03-Estrutural/Rateio',
      Status_Pagamento: 'Pendente',
      Macroconta_Inttegra: '6. SUPORTE PRODUÇÃO (Custos Indiretos)',
      Categoria_Inttegra: 'Administração',
      Subcategoria_Detalhe: '',
    },
  ],
  maquinario: [{ id: 'm1', name: 'Trator John Deere 5075', horimetro: 1510, nextRevision: 1500 }],
  clima: [{ id: 'c1', date: new Date().toISOString(), pluviometria: 15 }],
  auditLogs: [
    {
      id: 'al1',
      date: new Date(new Date().getTime() - 86400000).toISOString(),
      userName: 'Admin CEO',
      action: 'Update',
      table: 'Animais',
      recordId: '001',
      oldValue: '540',
      newValue: '550',
    },
  ],
  inttegraConfig: {
    token: '',
    baseUrl: 'https://api.inttegra.com/v1/',
    status: 'Desconectado',
    lastSync: null,
  },
  syncMappings: [],
  importLogs: [],
}
