import { AppState, User } from './types'

export const mockUsers: User[] = [
  { id: 'u1', email: 'admin@agro.com', name: 'Admin CEO', role: 1, phone: '+5511999999991' },
  { id: 'u2', email: 'gerente@agro.com', name: 'Gerente', role: 2, phone: '+5511999999992' },
  { id: 'u3', email: 'peao@agro.com', name: 'Operacional', role: 3, phone: '+5511999999993' },
]

export const initialData: AppState = {
  isAuthenticated: false,
  currentUser: null,
  notifiedAlertIds: [],
  userRole: 1,
  isOnline: true,
  pendingSyncQueue: [],
  lastSync: new Date().toISOString(),
  pastos: [
    {
      id: 'p1',
      name: 'Piquete Maternidade',
      status: 'Ocupado',
      loteId: 'l1',
      grassHeight: 18,
      capacity: 50,
      area: 12,
      taxaLotacao: 45,
      idealEntryHeight: 35,
      minExitHeight: 20,
    },
    {
      id: 'p2',
      name: 'Pasto Fundo',
      status: 'Livre',
      grassHeight: 40,
      capacity: 100,
      area: 25,
      taxaLotacao: 0,
      idealEntryHeight: 35,
      minExitHeight: 20,
    },
  ],
  lotes: [
    { id: 'l1', name: 'Matrizes PO Elite', costCenter: 'CC01-PO' },
    { id: 'l2', name: 'Garrotes Engorda TIP', costCenter: 'CC02-TIP' },
  ],
  animais: [
    {
      id: 'a1',
      brinco: '001',
      rgn: 'NEL123',
      loteId: 'l1',
      categoria: 'Matriz',
      pesoEntrada: 400,
      pesoAtual: 550,
      gmd: 0.1,
      status: 'Ativo',
      birthDate: '2020-05-10',
      costCenter: 'CC01-PO',
      gender: 'F',
    },
    {
      id: 'a3',
      brinco: '101',
      loteId: 'l2',
      categoria: 'Garrote',
      pesoEntrada: 250,
      pesoAtual: 320,
      gmd: 1.2,
      status: 'Ativo',
      birthDate: '2023-08-20',
      costCenter: 'CC02-TIP',
      gender: 'M',
    },
  ],
  pesagens: [{ id: 'ps1', animalId: 'a1', weight: 500, date: '2023-08-01T10:00:00.000Z' }],
  reproducoes: [
    {
      id: 'r1',
      animalId: 'a1',
      type: 'IATF',
      date: '2023-10-01',
      previsaoToque: '2023-10-31',
      dpp: new Date(new Date().getTime() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'Prenhe',
    },
  ],
  estoque: [
    {
      id: 'e1',
      name: 'Ração Proteica TIP',
      category: 'Nutrição',
      quantity: 5000,
      unit: 'Kg',
      unitCost: 2.5,
    },
    {
      id: 'e2',
      name: 'Vacina Aftosa',
      category: 'Saúde',
      quantity: 200,
      unit: 'Doses',
      unitCost: 1.8,
    },
  ],
  manejos: [
    {
      id: 'mn1',
      type: 'Nutrição',
      details: 'Trato Diário',
      date: new Date(Date.now() - 2 * 86400000).toISOString(),
      loteId: 'l2',
      cost: 1250,
      itemId: 'e1',
      quantity: 500,
    },
    {
      id: 'mn2',
      type: 'Nutrição',
      details: 'Trato Diário',
      date: new Date(Date.now() - 1 * 86400000).toISOString(),
      loteId: 'l2',
      cost: 1300,
      itemId: 'e1',
      quantity: 520,
    },
  ],
  transacoes: [
    {
      id: 't1',
      description: 'Venda Bezerros Mestiços',
      value: 45000,
      type: 'Receita',
      date: new Date().toISOString(),
      costCenter: 'CC02-TIP',
      status: 'Pago',
    },
    {
      id: 't3',
      description: 'Sêmen Elite ABS',
      value: 5000,
      type: 'Despesa',
      date: new Date().toISOString(),
      costCenter: 'CC01-PO',
      status: 'Pendente',
      due_date: new Date(new Date().getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
  maquinario: [{ id: 'm1', name: 'Trator John Deere 5075', horimetro: 1510, nextRevision: 1500 }],
  clima: [{ id: 'c1', date: new Date().toISOString(), pluviometria: 15 }],
  auditLogs: [
    {
      id: 'al1',
      date: new Date(new Date().getTime() - 86400000).toISOString(),
      userName: 'Admin CEO',
      action: 'Update',
      table: 'Animais',
      recordId: '001',
      oldValue: '540',
      newValue: '550',
    },
  ],
}
