import {
  LayoutDashboard,
  TrendingUp,
  Activity,
  Database,
  Globe,
  DollarSign,
  FileText,
  Settings,
  Bot,
  BrainCircuit,
  Link as LinkIcon,
  Upload,
  Map,
  Box,
  Scale,
  ArrowLeftRight,
  SplitSquareHorizontal,
  Baby,
  Package,
  Wrench,
  PieChart,
  Factory,
  Landmark,
  Users,
  CalendarDays,
  Tractor,
  LineChart,
  CloudSun,
  Bell,
  ShieldCheck,
  ShoppingCart,
} from 'lucide-react'

export const navigationMenu = [
  {
    title: 'Geral',
    items: [
      { title: 'Dashboard', url: '/', icon: LayoutDashboard },
      { title: 'Desempenho', url: '/desempenho', icon: TrendingUp },
      { title: 'Assistente IA', url: '/assistente-ia', icon: Bot },
      { title: 'Inteligência Artificial', url: '/inteligencia-artificial', icon: BrainCircuit },
      { title: 'Notificações', url: '/notificacoes', icon: Bell, badge: true },
    ],
  },
  {
    title: 'Rebanho & Estrutura',
    items: [
      { title: 'Animais', url: '/animais', icon: Activity },
      { title: 'Lotes', url: '/lotes', icon: Box },
      { title: 'Pastos', url: '/pastos', icon: Map },
      { title: 'Pesagem', url: '/pesagem', icon: Scale },
      { title: 'Importar Animais (IA)', url: '/importar-animais', icon: Upload },
      { title: 'Reclassificação', url: '/reclassificacao', icon: ArrowLeftRight },
      { title: 'Apartação', url: '/apartacao', icon: SplitSquareHorizontal },
      { title: 'Reprodução', url: '/reproducao', icon: Baby },
    ],
  },
  {
    title: 'Suprimentos',
    items: [
      { title: 'Estoque', url: '/estoque', icon: Package },
      { title: 'Manejo', url: '/manejo', icon: Wrench },
      { title: 'Previsão de Demanda', url: '/previsao-demanda', icon: PieChart },
      { title: 'Fábrica de Ração', url: '/fabrica-racao', icon: Factory },
    ],
  },
  {
    title: 'Financeiro',
    items: [
      { title: 'Financeiro', url: '/financeiro', icon: DollarSign },
      { title: 'Transações', url: '/transacoes', icon: Landmark },
      { title: 'Recebimento de Boletos', url: '/recebimento-boletos', icon: DollarSign },
      { title: 'Fluxo de Caixa', url: '/fluxo-de-caixa', icon: LineChart },
      { title: 'Parceiros', url: '/parceiros', icon: Users },
      { title: 'Gestão de Vendas', url: '/vendas/gestao', icon: ShoppingCart },
      { title: 'Vendas', url: '/vendas/geral', icon: ShoppingCart },
      { title: 'Eventos Comerciais', url: '/eventos-comerciais', icon: CalendarDays },
      { title: 'Eventos de Venda', url: '/vendas/eventos', icon: CalendarDays },
    ],
  },
  {
    title: 'Operações',
    items: [
      { title: 'Maquinário', url: '/maquinario', icon: Tractor },
      { title: 'Clima', url: '/clima', icon: CloudSun },
    ],
  },
  {
    title: 'Administração',
    items: [
      { title: 'Cadastros', url: '/cadastros', icon: Database },
      { title: 'Relatórios', url: '/relatorios', icon: FileText },
      { title: 'Auditoria', url: '/auditoria', icon: Activity },
      { title: 'Inttegra', url: '/inttegra', icon: LinkIcon },
      { title: 'Integrações', url: '/integracoes', icon: Globe },
      { title: 'Importação', url: '/importacao', icon: Upload },
      { title: 'QA & Integridade', url: '/qa-dashboard', icon: ShieldCheck },
      { title: 'Configurações', url: '/configuracoes', icon: Settings },
    ],
  },
]
