import {
  LayoutDashboard,
  TrendingUp,
  Target,
  BarChart,
  Activity,
  Database,
  Globe,
  DollarSign,
  FileText,
  Settings,
  Bot,
  BrainCircuit,
  Link as LinkIcon,
  Upload,
  Map,
  Box,
  Scale,
  ArrowLeftRight,
  SplitSquareHorizontal,
  Baby,
  Package,
  Wrench,
  PieChart,
  Factory,
  Landmark,
  Users,
  CalendarDays,
  Tractor,
  LineChart,
  CloudSun,
  Bell,
  ShieldCheck,
  ShoppingCart,
} from 'lucide-react'

export const navigationMenu = [
  {
    title: 'Gestão Estratégica',
    items: [
      { title: 'Diagnóstico Inicial', url: '/diagnostico-inicial', icon: Target, roles: [1] },
      { title: 'Metas e KPIs', url: '/metas-kpis', icon: BarChart, roles: [1] },
    ],
  },
  {
    title: 'Geral',
    items: [
      { title: 'Dashboard', url: '/', icon: LayoutDashboard, roles: [1] },
      { title: 'Desempenho', url: '/desempenho', icon: TrendingUp, roles: [1, 2, 3] },
      { title: 'Assistente IA', url: '/assistente-ia', icon: Bot, roles: [1, 2, 3] },
      {
        title: 'Inteligência Artificial',
        url: '/inteligencia-artificial',
        icon: BrainCircuit,
        roles: [1, 2, 3],
      },
      { title: 'Notificações', url: '/notificacoes', icon: Bell, badge: true, roles: [1, 2, 3] },
    ],
  },
  {
    title: 'Rebanho & Estrutura',
    items: [
      { title: 'Animais', url: '/animais', icon: Activity, roles: [1, 3] },
      { title: 'Maternidade', url: '/maternidade', icon: Baby, roles: [1, 3] },
      { title: 'Lotes', url: '/lotes', icon: Box, roles: [1, 3] },
      { title: 'Pastos', url: '/pastos', icon: Map, roles: [1, 3] },
      { title: 'Pesagem', url: '/pesagem', icon: Scale, roles: [1, 3] },
      { title: 'Importar Animais (IA)', url: '/importar-animais', icon: Upload, roles: [1, 3] },
      { title: 'Reclassificação', url: '/reclassificacao', icon: ArrowLeftRight, roles: [1, 3] },
      { title: 'Apartação', url: '/apartacao', icon: SplitSquareHorizontal, roles: [1, 3] },
      { title: 'Reprodução', url: '/reproducao', icon: Baby, roles: [1, 3] },
    ],
  },
  {
    title: 'Suprimentos',
    items: [
      { title: 'Estoque', url: '/estoque', icon: Package, roles: [1] },
      { title: 'Manejo', url: '/manejo', icon: Wrench, roles: [1] },
      { title: 'Previsão de Demanda', url: '/previsao-demanda', icon: PieChart, roles: [1] },
      { title: 'Fábrica de Ração', url: '/fabrica-racao', icon: Factory, roles: [1] },
    ],
  },
  {
    title: 'Financeiro',
    items: [
      { title: 'Financeiro', url: '/financeiro', icon: DollarSign, roles: [1, 2] },
      { title: 'Transações', url: '/transacoes', icon: Landmark, roles: [1, 2] },
      { title: 'Despesas e Pagamentos', url: '/despesas', icon: DollarSign, roles: [1, 2] },
      {
        title: 'Controle de Recebimento',
        url: '/controle-recebimento',
        icon: DollarSign,
        roles: [1, 2, 3],
      },
      { title: 'Fluxo de Caixa', url: '/fluxo-de-caixa', icon: LineChart, roles: [1, 2] },
      { title: 'Parceiros', url: '/parceiros', icon: Users, roles: [1, 3] },
      { title: 'Gestão de Vendas', url: '/vendas/gestao', icon: ShoppingCart, roles: [1, 2] },
      { title: 'Vendas', url: '/vendas/geral', icon: ShoppingCart, roles: [1, 2] },
      {
        title: 'Eventos Comerciais',
        url: '/eventos-comerciais',
        icon: CalendarDays,
        roles: [1, 2],
      },
      { title: 'Eventos de Venda', url: '/vendas/eventos', icon: CalendarDays, roles: [1, 2, 3] },
    ],
  },
  {
    title: 'Operações',
    items: [
      { title: 'Maquinário', url: '/maquinario', icon: Tractor, roles: [1] },
      { title: 'Clima', url: '/clima', icon: CloudSun, roles: [1] },
    ],
  },
  {
    title: 'Administração',
    items: [
      { title: 'Cadastros', url: '/cadastros', icon: Database, roles: [1, 2, 3] },
      { title: 'Relatórios', url: '/relatorios', icon: FileText, roles: [1, 2] },
      { title: 'Auditoria', url: '/auditoria', icon: Activity, roles: [1] },
      { title: 'Inttegra', url: '/inttegra', icon: LinkIcon, roles: [1] },
      { title: 'Integrações', url: '/integracoes', icon: Globe, roles: [1] },
      { title: 'Importação', url: '/importacao', icon: Upload, roles: [1] },
      { title: 'QA & Integridade', url: '/qa-dashboard', icon: ShieldCheck, roles: [1] },
      { title: 'Configurações', url: '/configuracoes', icon: Settings, roles: [1] },
    ],
  },
]
